name: Update emojis

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Export emojis
        run: yarn export

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Olyno
          author_email: ${{ secrets.EMAIL }}
          message: Updated emojislist
          add: emojis.json
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
