name: Update emojis

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Load cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Export emojis
        run: yarn export
        env:
          DEBUG: emojis

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Olyno
          author_email: ${{ secrets.EMAIL }}
          message: 'build(emojis): update list'
          add: emojis.json
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
